In [ ]:
# In this notebook, we will perform hypothesis testing to determine if there is a significant difference in billing amounts based on Gender. I have taken this data set from Kaggle and it had a large sample size of more than 1000 records. I randomly selected 50 records from the data set to perform the hypothesis testing.

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [4]:
import scipy.stats as st

In [5]:
df = pd.read_csv("random_50_samples.csv")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,mIchAEl thOrnTon mD,57,Male,O+,Diabetes,2023-09-15,Jason Hanson,Thornton-Roy,Medicare,3616.898450,339,Elective,2023-10-02,Aspirin,Inconclusive
1,mattheW HUTcHiNsOn,51,Female,A+,Diabetes,2023-10-07,Jesse Gonzalez,Wilkerson-Lewis,Aetna,36970.075481,372,Emergency,2023-10-14,Penicillin,Abnormal
2,RoNald paRK,20,Male,A+,Asthma,2019-09-09,Sarah Hernandez,Brown-Hughes,Blue Cross,44393.001348,148,Elective,2019-10-08,Penicillin,Inconclusive
3,Jeff BroOkS,74,Female,B+,Obesity,2020-09-14,Cathy Sanchez,"Wilson, Alexander Wolf and",Aetna,27554.923708,135,Emergency,2020-09-21,Ibuprofen,Abnormal
4,TAnya THoMPsOn,56,Male,AB-,Obesity,2023-02-01,Nancy Lee,"Winters, Blackburn Chandler and",Aetna,27466.318567,284,Emergency,2023-02-07,Paracetamol,Inconclusive
5,EThan MItcHELL,46,Male,B+,Cancer,2021-12-30,Christina Hart,Rocha-Wagner,Medicare,4802.620714,175,Elective,2022-01-27,Paracetamol,Abnormal
6,AMBer WRiGHt,44,Female,O+,Asthma,2023-05-13,Melissa Stephens,Friedman-Douglas,Blue Cross,40207.463218,336,Elective,2023-06-09,Paracetamol,Inconclusive
7,mORGAn lAWreNce,46,Male,B-,Diabetes,2023-06-20,Paul Hansen,"Wells and Davila Cooper,",Medicare,30065.260598,212,Elective,2023-07-16,Ibuprofen,Abnormal
8,MackEnZiE MAxwEll,64,Female,AB-,Arthritis,2019-08-03,Thomas Pratt,"and Alvarez, Cox Powers",Cigna,392.913548,113,Urgent,2019-08-15,Ibuprofen,Inconclusive
9,Cindy ROGeRS,68,Male,B-,Cancer,2022-03-15,Calvin George,"Conley Jackson, and Hill",Medicare,20886.342148,274,Urgent,2022-04-14,Penicillin,Normal
10,JOSEph sanCHeZ,50,Female,B+,Arthritis,2020-12-19,Rhonda Callahan,"and Perez, Bradford Evans",Aetna,2942.481598,267,Emergency,2020-12-25,Lipitor,Inconclusive
11,rYAn mArTiN,57,Female,B-,Obesity,2019-12-15,Angel Ford,Nichols-Martin,Cigna,2149.818465,296,Emergency,2020-01-10,Paracetamol,Abnormal
12,Joshua rogErS,72,Male,B+,Obesity,2023-03-10,Glenn Cain,LLC Grimes,UnitedHealthcare,13677.980570,469,Urgent,2023-03-15,Ibuprofen,Inconclusive
13,alliSON sparkS,23,Male,O+,Cancer,2023-01-06,Kyle Jones,"Cox, Meyer Manning and",Blue Cross,44695.848909,491,Urgent,2023-01-18,Lipitor,Inconclusive
14,laurA coOPer,27,Male,B+,Obesity,2022-12-18,Joseph Richardson,"Mckenzie and Gonzalez Cruz,",Blue Cross,43304.925165,241,Emergency,2023-01-10,Lipitor,Abnormal
15,cHrIsTinE lOpEZ,71,Female,AB-,Diabetes,2019-11-20,Alison Cole,Inc Shaw,Blue Cross,8220.097214,307,Urgent,2019-12-09,Paracetamol,Normal
16,kRisteN HALl,44,Female,A-,Asthma,2023-02-20,Nicholas Sandoval,and Sons Pham,Cigna,43779.915515,209,Urgent,2023-03-07,Aspirin,Abnormal
17,emmA CoRtez,66,Male,O-,Diabetes,2022-09-07,Adam Green,Rodriguez Inc,Blue Cross,30107.936570,173,Elective,2022-10-04,Ibuprofen,Abnormal
18,roBErt MEDINA,33,Male,AB+,Diabetes,2022-03-09,Alison Nash,"Stanton and Harding, Hicks",Aetna,18494.663891,486,Emergency,2022-03-21,Ibuprofen,Normal
19,caSsANdRA HerNanDEz,33,Female,B-,Cancer,2019-08-06,Steven Hardin,"Peterson and Williams Johnson,",Blue Cross,32721.060944,253,Urgent,2019-08-22,Penicillin,Inconclusive
20,sUe loPEZ,69,Male,B+,Diabetes,2020-04-20,Robert Meyers,Pearson-Gibson,Aetna,33723.788238,136,Emergency,2020-05-19,Ibuprofen,Normal
21,miChAEL WooD,67,Female,O-,Arthritis,2023-02-03,Jose Delgado,Stone-Warren,Aetna,27965.158943,367,Urgent,2023-02-16,Aspirin,Abnormal
22,daRRyl jOhnSon,41,Male,B+,Diabetes,2022-04-06,Amber Donaldson,"Horne and Thomas Hubbard,",Medicare,31481.657930,206,Emergency,2022-04-23,Penicillin,Normal
23,Sydney lOVE,68,Female,B+,Asthma,2020-07-29,Catherine Garrett,Group Mayer,Cigna,25025.742988,114,Emergency,2020-08-09,Penicillin,Abnormal
24,RiChARD RoberTs,57,Female,O-,Obesity,2019-12-13,Alicia Wade,"and Knox Flores, Christian",Medicare,16928.787864,489,Elective,2020-01-01,Lipitor,Inconclusive
25,mrs. sabrInA mOrEnO,78,Female,A+,Diabetes,2020-10-05,Jessica Byrd,"Bryant and Thomas, Smith",Aetna,16267.126607,253,Elective,2020-10-14,Paracetamol,Normal
26,JENNIFer grAves,24,Female,A+,Obesity,2022-02-14,Zachary Brown,Ortiz-Olson,Medicare,20102.842601,380,Emergency,2022-02-15,Penicillin,Abnormal
27,heatHER BRoOKS,29,Female,A-,Arthritis,2019-06-29,Erin Guerra,Baker PLC,UnitedHealthcare,4569.733306,376,Urgent,2019-07-17,Lipitor,Inconclusive
28,WANda hiCKMAn,60,Male,O+,Asthma,2019-12-13,Edward Johnson,Myers PLC,Medicare,3213.065912,408,Elective,2020-01-11,Lipitor,Normal
29,mIrANDA DiAZ,78,Male,O+,Obesity,2020-12-27,Stephen Brown,Leonard-Chapman,Blue Cross,22457.218710,460,Elective,2021-01-06,Aspirin,Abnormal
30,gRegOry BErry,85,Female,B-,Arthritis,2023-07-12,Scott Stewart,and Smith Sons,Aetna,8545.666840,363,Elective,2023-07-25,Paracetamol,Abnormal
31,MeGHAn fLOREs,61,Male,B+,Cancer,2023-04-06,Bethany Green,"Esparza Mitchell, and Gamble",Aetna,7671.832016,333,Emergency,2023-04-29,Lipitor,Abnormal
32,ShAnnoN PaTtersON,77,Male,A+,Asthma,2022-05-02,Kelly Santos,Doyle-West,Cigna,4145.422096,465,Emergency,2022-05-27,Lipitor,Normal
33,MiCHeLE feRNandez,30,Female,AB+,Cancer,2022-06-05,Amber Henry,and Sons Beasley,Aetna,22655.097594,388,Urgent,2022-06-21,Aspirin,Normal
34,JOHn jOHNsON,44,Male,A+,Obesity,2022-09-26,Erika Tucker,Inc Harris,Medicare,19526.348812,341,Urgent,2022-10-11,Paracetamol,Inconclusive
35,DaViD hALey,76,Female,B+,Cancer,2022-04-07,Barbara Ellis,Hill-Guzman,Cigna,1924.337934,269,Elective,2022-04-16,Penicillin,Inconclusive
36,TamaRa hArT,31,Female,O-,Arthritis,2022-12-09,Lisa Jones,LLC Mendoza,UnitedHealthcare,1801.034632,224,Urgent,2022-12-21,Ibuprofen,Inconclusive
37,NaNCY meLtON,62,Female,AB-,Asthma,2022-12-31,Blake Flores MD,Francis-Cook,Cigna,13807.569583,210,Elective,2023-01-25,Paracetamol,Abnormal
38,MR. keIth NelSon,74,Male,A+,Hypertension,2021-04-05,Pamela Martinez,Rodriguez-Martin,Blue Cross,11369.785005,317,Urgent,2021-04-14,Aspirin,Abnormal
39,JuAN BaiLEY,38,Male,B-,Diabetes,2024-04-17,Jeffrey Campos,"Rogers, and Sanford Henry",Medicare,6366.410183,450,Urgent,2024-05-12,Paracetamol,Abnormal
40,tIMOThY BAiLey,30,Female,O-,Asthma,2021-02-20,Kayla Levine,"and Jones Perez, Brown",Cigna,6719.846524,486,Emergency,2021-03-15,Ibuprofen,Inconclusive
41,MIchelLE Diaz,25,Male,O+,Obesity,2022-12-20,Dana Martinez,Inc Davis,Medicare,47749.017060,258,Urgent,2022-12-30,Lipitor,Normal
42,MIChAeL contreraS,63,Male,A-,Obesity,2022-07-25,Amy Small,Wang-Hill,Medicare,17159.581532,330,Emergency,2022-08-22,Ibuprofen,Normal
43,rOBErT MCcarThy,85,Female,O+,Arthritis,2022-07-16,Tommy Baker,"Long and Aguilar Delgado,",Aetna,28347.693926,437,Elective,2022-07-31,Paracetamol,Inconclusive
44,KRiStEN cOhEn,78,Female,O-,Asthma,2024-01-06,Brandy Nichols,Ltd Stewart,Aetna,14687.499950,155,Elective,2024-01-31,Aspirin,Normal
45,stEven lOVe,56,Male,A+,Obesity,2023-11-23,Colleen Noble,Hamilton-Wright,Cigna,28796.456347,194,Emergency,2023-12-20,Lipitor,Abnormal
46,jaNET HUGhes,64,Male,AB+,Asthma,2020-04-07,Tyrone Griffin,Jones-Watkins,UnitedHealthcare,21502.800082,480,Elective,2020-04-20,Aspirin,Normal
47,BrAd mUeLLer,79,Male,A+,Obesity,2021-07-28,Lisa Lopez,Taylor PLC,Cigna,27778.576108,292,Urgent,2021-08-17,Aspirin,Abnormal
48,MicHELLE cAnnOn,85,Female,O-,Hypertension,2023-09-27,Brooke Smith,"Livingston Miller, and Dixon",Aetna,33942.844498,419,Elective,2023-10-15,Ibuprofen,Inconclusive
49,LeAH ONEAL,19,Male,B-,Cancer,2023-12-07,Lisa Stewart,Ltd Porter,Cigna,42031.356181,344,Urgent,2023-12-24,Paracetamol,Abnormal

In [ ]:
fig = px.box(
    df,
    x="Gender",
    y="Billing Amount",
    color="Gender",
    title="Billing Amount by Gender",
    labels={"Billing Amount": "Bill Amount", "Gender": "Gender"},
)
fig.show()

In [7]:
df["Billing Amount"].describe()

count       50.000000
mean     20894.296932
std      13888.817582
min        392.913548
25%       7808.898315
50%      20494.592375
75%      30097.267577
max      47749.017060
Name: Billing Amount, dtype: float64

In [ ]:
# Hypothesis Testing:
# Null Hypothesis (H0): There is no significant difference in billing amounts based on Gender.
# Alternative Hypothesis (H1): There is a significant difference in billing amounts based on Gender

In [10]:
df.groupby("Gender")["Billing Amount"].describe()

,count,mean,std,min,25%,50%,75%,max
Gender,,,,,,,,
Female,24.0,18259.572228,13503.910993,392.913548,6182.318219,16597.957236,28060.792689,43779.915515
Male,26.0,23326.350505,14053.461891,3213.065912,11946.833896,21980.009396,31138.227590,47749.017060

In [ ]:
# In this case I have used Welch's t-test because it does not assume equal variances between the two. There was not a huge difference in the standard deviations of the two groups, but I wanted to be cautious given the small sample size.

alpha = 0.05

male_billing = df[df["Gender"] == "Male"]["Billing Amount"]
female_billing = df[df["Gender"] == "Female"]["Billing Amount"]

t_stat, p_value = st.ttest_ind(male_billing, female_billing, equal_var=False)

print(f"Welch's t-test Results")
print(f"----------------------")
print(f"T-statistic : {t_stat:.4f}")
print(f"P-value     : {p_value:.4f}")
print(f"Alpha       : {alpha}")
print()
if p_value < alpha:
    print("Result: Reject the Null Hypothesis.")
    print(
        "There IS a significant difference in billing amounts between Male and Female."
    )
else:
    print("Result: Fail to Reject the Null Hypothesis.")
    print(
        "There is NO significant difference in billing amounts between Male and Female."
    )

Welch's t-test Results
----------------------
T-statistic : 1.2998
P-value     : 0.1999
Alpha       : 0.05

Result: Fail to Reject the Null Hypothesis.
There is NO significant difference in billing amounts between Male and Female.